/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ivanzkyanto.ttt;

import org.junit.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Main classUnderTest = new Main();
        classUnderTest.getClass();
    }
}
