/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ivanzkyanto.ttt;

import com.ivanzkyanto.ttt.game.Game;

public class Main {
    public static void main(String[] args) {
        Game game = new Game();
        game.getClass(); 
    }
}
